### ISSUE TITLE
Encoding error in `ramp_test_submission`

### ISSUE THREAD

**Issue by aboucaud** [paris-saclay-cds/ramp-workflow#115]
I just received a feedback from a user

```
[rhlozek@midway-login2 supernovae]$ ~/.local/bin/ramp_test_submission --quick-test
Testing PLAsTiCC transient classification RAMP
Reading train and test files from ./data ...
Reading cv ...
Training ./submissions/starting_kit ...
CV fold 0
score   auc   acc   nll
train  1.00  1.00  0.11
valid  0.85  0.75  0.47
test   0.74  0.59  0.89

CV fold 1
score   auc   acc   nll
train  1.00  1.00  0.12
valid  0.86  0.75  0.46
test   0.79  0.68  0.65

CV fold 2
score   auc   acc   nll
train  1.00  0.99  0.12
valid  0.85  0.78  0.47
test   0.80  0.61  1.40

----------------------------
Mean CV scores
----------------------------

Traceback (most recent call last):
  File "/home/rhlozek/.local/bin/ramp_test_submission", line 11, in <module>
    load_entry_point('ramp-workflow==0.2.0+23.g7a4b7e0', 'console_scripts', 'ramp_test_submission')()
  File "/home/rhlozek/.local/lib/python3.5/site-packages/rampwf/utils/command_line.py", line 85, in ramp_test_submission
    retrain=retrain)
  File "/home/rhlozek/.local/lib/python3.5/site-packages/rampwf/utils/testing.py", line 582, in assert_submission
    _print_df_scores(df_mean_scores, score_types, indent='\t')
  File "/home/rhlozek/.local/lib/python3.5/site-packages/rampwf/utils/testing.py", line 262, in _print_df_scores
    print('\n'.join(df_repr_out))
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 118: ordinal not in range(128)
```

@glemaitre @jorisvandenbossche any idea ?

I just asked for the OS name and version.

**Comment by aboucaud** [comment]
```
Linux midway-login1 2.6.32-696.18.7.el6.x86_64 #1 SMP Wed Jan 3 19:31:16 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by agramfort** [comment]
I am sure they use python3. We saw this with students on fake news ramp

**Comment by aboucaud** [comment]
The ramp-workflow is tested against python3...

**Comment by agramfort** [comment]
yes but if they write a feature extraction with unicode characters...

**Comment by jorisvandenbossche** [comment]
It seems to happen when printing the scores table. But it is strange that printing a dataframe with scores gives unicode errors .. Fancy score names?

**Comment by jorisvandenbossche** [comment]
Ah no I see, it is the table with mean scores.    So it will error on the +/- sign

**Comment by aboucaud** [comment]
But why suddently ?

**Comment by glemaitre** [comment]
I should get the error when testing the kits, isn't it?

**Comment by aboucaud** [comment]
Could it happen through the bad configuration of a text editor if someone opens the file and saves it back ?

**Comment by jorisvandenbossche** [comment]
Might be related to their shell: https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20#comment19202573_9942822

**Comment by aboucaud** [comment]
@jorisvandenbossche found the bug might be related to the wrong encoding of the shell and thus a possible solution by setting the environment variable `PYTHONIOENCODING`
```
export PYTHONIOENCODING=utf-8
```
