### ISSUE TITLE
Keras import failure

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-workflow#141]
@F3kih reported experiencing issues with importing keras in the drug_spectra_M2IMDS_2018 challenge (userid: Fkih, runid: 45_ClassifTunedCN2), while the import worked before.

<details>
<summary>See full traceback</summary>

```pytb
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/ramp_test_submission", line 11, in <module>
    load_entry_point('ramp-workflow==0.2.0+35.g00a6ff3', 'console_scripts', 'ramp_test_submission')()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ramp_workflow-0.2.0+35.g00a6ff3-py3.6.egg/rampwf/utils/command_line.py", line 86, in ramp_test_submission
    retrain=retrain)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ramp_workflow-0.2.0+35.g00a6ff3-py3.6.egg/rampwf/utils/testing.py", line 114, in assert_submission
    fold, ramp_data_dir)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ramp_workflow-0.2.0+35.g00a6ff3-py3.6.egg/rampwf/utils/submission.py", line 151, in run_submission_on_cv_fold
    fold_output_path, train_is=train_is)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ramp_workflow-0.2.0+35.g00a6ff3-py3.6.egg/rampwf/utils/submission.py", line 91, in train_test_submission
    module_path, X_train, y_train, train_is=train_is)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ramp_workflow-0.2.0+35.g00a6ff3-py3.6.egg/rampwf/workflows/drug_spectra.py", line 25, in train_submission
    train_submission(module_path, X_train_df, y_train_clf_array)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ramp_workflow-0.2.0+35.g00a6ff3-py3.6.egg/rampwf/workflows/feature_extractor_classifier.py", line 21, in train_submission
    module_path, X_train_array, y_array[train_is])
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ramp_workflow-0.2.0+35.g00a6ff3-py3.6.egg/rampwf/workflows/classifier.py", line 12, in train_submission
    classifier = import_file(module_path, self.element_names[0])
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ramp_workflow-0.2.0+35.g00a6ff3-py3.6.egg/rampwf/utils/importing.py", line 32, in import_file
    submitted_module = imp.load_source(submitted_path, submitted_file)
  File "/home/ubuntu/miniconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./submissions/submission_000008462/classifier.py", line 17, in <module>
    from keras.wrappers.scikit_learn import KerasClassifier
ModuleNotFoundError: No module named 'keras'
mprof: Sampling memory every 0.1s
```
</details>

The error message can also be found in 

[https://www.ramp.studio/9763becb6e82a80528732f930f24a95488be2dd8/error.txt](https://www.ramp.studio/9763becb6e82a80528732f930f24a95488be2dd8/error.txt)

Could something have changed in the environement with the latest RAMP challenges?

**Comment by kegl** [comment]
We'll add it and relaunch the jobs. Please use slack for these pings since it's unrelated to the library.

**Comment by rth** [comment]
Thank you @kegl !
