### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by GuillaumeDesforges** [paris-saclay-cds/ramp-workflow#192]
I am packaging current version from GitHub on Nix.

When doing the checks (aka tests), I have an error:

```
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 80, in <module>
    'ramp_leaderboard='
  File "/nix/store/i1xm831hj7wncmh6xb532flr7i522l04-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/nix/store/i1xm831hj7wncmh6xb532flr7i522l04-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/command/test.py", line 237, in run
    self.run_tests()
  File "/nix/store/i1xm831hj7wncmh6xb532flr7i522l04-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/command/test.py", line 259, in run_tests
    exit=False,
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/loader.py", line 406, in _find_tests
    full_path, pattern, namespace)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/nix/store/i1xm831hj7wncmh6xb532flr7i522l04-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/nix/store/i1xm831hj7wncmh6xb532flr7i522l04-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/nix/store/i1xm831hj7wncmh6xb532flr7i522l04-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/loader.py", line 212, in loadTestsFromName
    (obj, test))
TypeError: calling <class 'rampwf.externals.colored.back.back'> returned <rampwf.externals.colored.back.back object at 0x7fffcc6b9990>, not a test
```

**Comment by agramfort** [comment]
@GuillaumeDesforges how can we replicate this?

we use https://github.com/paris-saclay-cds/ramp-workflow/blob/master/.travis.yml travis for testing and it's currently green.

**Comment by agramfort** [comment]
see https://travis-ci.org/paris-saclay-cds/ramp-workflow

**Comment by agramfort** [comment]
actually it's currently red... @lucyleeow can you have a look https://travis-ci.org/paris-saclay-cds/ramp-workflow/builds/621134042 ? thanks

**Comment by lucyleeow** [comment]
@agramfort it's red due to #196. I can look into it.

**Comment by kegl** [comment]
The imputer warning is fixed in this branch: 

https://github.com/paris-saclay-cds/ramp-workflow/pull/199

Feel free to merge it.
